### ISSUE TITLE
First instance is alway processed even when unchecked

### ISSUE THREAD

**Issue by chadmv** [pyblish/pyblish-lite#113]
If there are multiple instances listed, if the first is unchecked, it will get processed anyways when the "Play" button is pressed.

![image](https://user-images.githubusercontent.com/974633/98887778-70e2f000-244b-11eb-81d6-f1b99792e649.png)

**Comment by mottosso** [comment]
Indeed, this is an issue as old as time itself.

- https://github.com/pyblish/pyblish-lite/issues/59

I think up till and including now, people have simply learnt to live with it (e.g. making a null instance be first) rather than actually try and address it, haha. A PR of this sort would help many people.

Also I'd like to highlight a PR from some time ago, addressing lots of issues (possibly this one as well) that needs just a small push over the finish line.

- https://github.com/pyblish/pyblish-lite/pull/109
